---
title: "README"
format: gfm
editor: visual
---

```{r}
#| echo: false
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

减重如山倒，增肌如抽丝。2022年写博士毕业论文的一个月体重减少了两公斤，之后去德国两个月又减少了两公斤，之后体重维持平稳。为了恢复体重，之后断断续续健身和增加热量摄入，无果。2024年春末夏初终于开始认真健身，企图将摄入的热量固定下来。通常每周训练3次，重点训练胸肌和肩背。两大肌群各有3-4个动作，每次训练中，每个动作做3组，每组8-15个重复。健身开始至今，尝试了约20个动作，以固定器械为主，下面两图展示最常练的几个动作的重量变化。

```{r dpi=300}
# Preparation ----
library(googlesheets4)
library(dplyr)
library(tidyr)
library(ggplot2)
library(showtext)
showtext_auto()

# Data ----
train_record <- read_sheet(
  ss = paste0(
    "https://docs.google.com/spreadsheets/", 
    "d/1pUFHIiLTAT3JexSDrs3fXUhE9urtcEPA57gzEI83r1M/", 
    "edit?gid=1837755800#gid=1837755800"
  ), 
  sheet = "训练内容", range = "A:F"
) %>% 
  select(
    "date" = "日期", "exercise" = "项目", 
    "weight" = "重量", "rep" = "次数", "set" = "组数"
  ) %>% 
  # 生成每个动作的次数，并以初始重量为1进行标准化。
  group_by(exercise) %>% 
  mutate(
    date_id = row_number(), 
    weight_init = first(weight), weight_scale = weight / weight_init
  ) %>% 
  ungroup()

# 次数较多项目的初始重量和当前重量。
train_first_last <- 
  train_record %>% 
  group_by(exercise) %>% 
  mutate(date_id_max = max(date_id)) %>% 
  ungroup() %>% 
  filter(date_id_max > 20) %>% 
  # 只保留初始重量和当前重量。
  filter(date_id == 1 | date_id == date_id_max) %>% 
  # 重命名初始重量和当前重量对应的日期ID。
  mutate(date_id = case_when(
    date_id == 1 ~ "初始重量", date_id == date_id_max ~ "当前重量"
  ))
# 对应的宽数据。
train_first_last_wide <- train_first_last %>% 
  pivot_wider(id_cols = exercise, names_from = date_id, values_from = weight)

# Analysis ----
# 全部项目的重量变化。
# ggplot(train_record) + 
#   geom_line(aes(date_id, weight_scale)) + 
#   facet_wrap(.~ exercise)

# 次数较多的项目的重量变化。
train_record %>% 
  group_by(exercise) %>% 
  mutate(date_id_max = max(date_id)) %>% 
  ungroup() %>% 
  filter(date_id_max > 20) %>% 
  ggplot() + 
  geom_line(aes(date_id, weight_scale, col = rep), size = 0.7) + 
  scale_color_gradient2(
    low = "darkgreen", high = "darkred", mid = "orange", midpoint = 12
  ) + 
  facet_wrap(.~ exercise) + 
  theme_bw() + 
  labs(x = "第N次训练", y = "重量标准化值")

# 可视化重量变化。
ggplot() + 
  geom_segment(
    data = train_first_last_wide, 
    aes(x = exercise, xend = exercise, y = `初始重量`, yend = `当前重量`), 
    col = "darkgrey", size = 1
  ) + 
  geom_point(
    data = train_first_last, 
    aes(exercise, weight, col = date_id), position = "identity"
  ) + 
  coord_flip() + 
  theme_bw() + 
  labs(x = "项目", y = "重量", col = "")
```
